### ISSUE TITLE
Boolean value is recognized as character string

### ISSUE THREAD

**Issue by tkikuchi2000** [nitr8/docker-creepminer#2]
Hi, awesome works!

I noticed that `AUTO_START`, `ENABLE_SSH` are always `true` regardless of their set value (`TRUE` or `FALSE`).

- fix typo in `helper/init`
- fix boolean value in `docker-compose.yaml` and `Dockerfile`

In my environment, this is working as expected. :)
Pull request is [here](https://github.com/nitr8/docker-creepminer/pull/1).

**Comment by nitr8** [comment]
@tkikuchi2000 - thanks man - will commit soon :) nice find & fix...
